version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "127.0.0.1:${INTERNAL_NGINX_PORT}:8080"
    restart: always
    links:
      - phpsv
      - translate
    depends_on:
      - phpsv
    volumes:
      - ./config/nginx-site.conf:/etc/nginx/conf.d/default.conf
      - ./src/subtitulamos/public:/code/public:cached
    logging:
      options:
        max-size: "600m"
        max-file: "3"

  phpsv:
    build:
      context: .
      dockerfile: Dockerfile.PHP
    working_dir: /code
    restart: always
    links:
      - redis
      - search
    depends_on:
      - search
    volumes:
      - ./.env:/code/.env
      - ./data/phpsess:/tmp/phpsess
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
    logging:
      options:
        max-size: "400m"
        max-file: "3"

  redis:
    image: redis:6.0-alpine
    restart: always
    volumes:
      - ./data/redis:/data

  search:
    image: getmeili/meilisearch:v0.19.0
    restart: always
    volumes:
      - ./data/search:/data.ms
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=${MEILI_ENV}

  translate:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.Go
      args:
        REDIS_PUBSUB_ENV: ${ENVIRONMENT_NAME}
    links:
      - redis
    logging:
      options:
        max-size: "100m"
        max-file: "3"
