version: '3'

# NOTE: This is a development-only docker-compose file
#       It is very similar to the production configuration, but less optimized

services:
  nginx:
    container_name: subs_nginx
    image: nginx:alpine
    ports:
      - "127.0.0.1:8080:8080"
    restart: on-failure
    links:
      - phpsv
      - translate
    depends_on:
      - phpsv
    volumes:
      - ./config/nginx-site.conf:/etc/nginx/conf.d/default.conf
      - ./src/subtitulamos/public:/code/public:cached

  phpsv:
    container_name: subs_phpsv
    image: subs_phpsv
    build:
      context: .
      dockerfile: Dockerfile.PHP
    working_dir: /code
    restart: on-failure
    links:
      - mariadb
      - redis
    volumes:
      - ./.env:/code/.env
      - ./src/subtitulamos/app:/code/app
      - ./src/subtitulamos/public:/code/public
      - ./src/subtitulamos/resources:/code/resources
      - ./src/subtitulamos/composer.json:/code/composer.json
      - ./src/subtitulamos/composer.lock:/code/composer.lock
      - ./src/subtitulamos/cli-config.php:/code/cli-config.php

  mariadb:
    container_name: subs_mariadb
    image: mariadb/server:10.4
    ports:
      - "127.0.0.1:33066:3306"
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ./data/mariadb:/var/lib/mysql

  redis:
    container_name: subs_redis
    image: redis:6.0-alpine
    volumes:
      - ./data/redis:/data

  sonic:
    container_name: subs_sonic
    image: valeriansaliou/sonic:v1.3.0
    volumes:
      - ./data/sonic:/var/lib/sonic/store/
      - ./config/sonic.cfg:/etc/sonic.cfg

  translate:
    container_name: subs_translate
    image: subs_translate
    build:
      context: .
      dockerfile: Dockerfile.Go
      args:
        TRANSLATE_SV_PORT: ${TRANSLATE_SV_PORT}
        REDIS_PUBSUB_ENV: ${ENVIRONMENT}
        REDIS_ADDR: ${REDIS_HOST}:${REDIS_PORT}
    links:
      - redis
