version: '3'

services:
  nginx:
    container_name: subs_nginx
    image: nginx:alpine
    ports:
      - "127.0.0.1:${INTERNAL_NGINX_PORT}:8080"
    restart: always
    links:
      - phpsv
      - translate
    depends_on:
      - phpsv
    volumes:
      - ./config/nginx-site.conf:/etc/nginx/conf.d/default.conf
      - ./src/subtitulamos/public:/code/public:cached

  phpsv:
    container_name: subs_phpsv
    image: subs_phpsv
    build:
      context: .
      dockerfile: Dockerfile.PHP
    working_dir: /code
    restart: always
    links:
      - redis
    volumes:
      - ./.env:/code/.env
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

  redis:
    container_name: subs_redis
    image: redis:6.0-alpine
    volumes:
      - ./data/redis:/data

  sonic:
    container_name: subs_sonic
    image: valeriansaliou/sonic:v1.3.0
    restart: always
    volumes:
      - ./data/sonic:/var/lib/sonic/store/
      - ./config/sonic.cfg:/etc/sonic.cfg

  translate:
    container_name: subs_translate
    image: subs_translate
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.Go
      args:
        TRANSLATE_SV_PORT: ${TRANSLATE_SV_PORT}
        REDIS_PUBSUB_ENV: ${ENVIRONMENT}
        REDIS_ADDR: ${REDIS_HOST}:${REDIS_PORT}
    links:
      - redis
