<?php

/**
 * This file is covered by the AGPLv3 license, which can be found at the LICENSE file in the root of this project.
 * @copyright 2017 subtitulamos.tv
 */

namespace App\Entities;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="shows")
 */
class Show
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="Episode", mappedBy="show")
     */
    private $episodes;

    /**
     * @ORM\Column(type="boolean", name="zero_tolerance")
     */
    private $zeroTolerance;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->episodes = new \Doctrine\Common\Collections\ArrayCollection();
    }

    ////////////////////////// AUTOGENERATED \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Show
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set zeroTolerance
     *
     * @param boolean $zeroTolerance
     *
     * @return Show
     */
    public function setZeroTolerance($zeroTolerance)
    {
        $this->zeroTolerance = $zeroTolerance;

        return $this;
    }

    /**
     * Get zeroTolerance
     *
     * @return boolean
     */
    public function getZeroTolerance()
    {
        return $this->zeroTolerance;
    }

    /**
     * Add episode
     *
     * @param \App\Entities\Episode $episode
     *
     * @return Show
     */
    public function addEpisode(\App\Entities\Episode $episode)
    {
        $this->episodes[] = $episode;

        return $this;
    }

    /**
     * Remove episode
     *
     * @param \App\Entities\Episode $episode
     */
    public function removeEpisode(\App\Entities\Episode $episode)
    {
        $this->episodes->removeElement($episode);
    }

    /**
     * Get episodes
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEpisodes()
    {
        return $this->episodes;
    }
}
