#!/usr/bin/env php
<?php

/**
 * This file is covered by the AGPLv3 license, which can be found at the LICENSE file in the root of this project.
 * @copyright 2020 subtitulamos.tv
 */

require __DIR__ . '/bootstrap.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new \App\Commands\ClearTwigCache());
$application->add(new \App\Commands\CreateUserBots());
$application->add(new \App\Commands\GenerateSitemaps());
$application->run();
